#!/bin/bash

cd $ROBOKOP_HOME/robokop/python
export CELERY_BROKER_URL="redis://$REDIS_HOST:$REDIS_PORT/$MANAGER_REDIS_DB"
export CELERY_RESULT_BACKEND="redis://$REDIS_HOST:$REDIS_PORT/$MANAGER_REDIS_DB"
export FLOWER_BROKER_API="redis://$REDIS_HOST:$REDIS_PORT/$MANAGER_REDIS_DB"
export FLOWER_PORT="$MANAGER_FLOWER_PORT"
export FLOWER_BASIC_AUTH="$FLOWER_USER:$FLOWER_PASSWORD"

if [[ -z CELERY_BROKER_URL ]]; then
    export CELERY_BROKER_URL="redis://$REDIS_HOST:$REDIS_PORT/$MANAGER_REDIS_DB"
fi
if [[ -z CELERY_RESULT_BACKEND ]]; then
    export CELERY_RESULT_BACKEND="redis://$REDIS_HOST:$REDIS_PORT/$MANAGER_REDIS_DB"
fi
if [[ -z FLOWER_PORT ]]; then
    export FLOWER_PORT=$MANAGER_FLOWER_PORT
fi

exec flower \
    -A tasks.celery \
    --broker=$CELERY_BROKER_URL \
    --broker_api=$CELERY_BROKER_URL